dist: xenial
sudo: required
language: python
cache: pip
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
services:
  - docker
install:
  - pip install tox-travis
script:
  - tox
after_failure:
  - echo "FUNNEL LOGS ----------"
  - cat ./tests/test_tmp/conformance_test_v1.0_*/funnel_log.txt
notifications:
  email: false
